// MASH Game Data - Extensive lists
const gameData = {
    home: {
        title: "Home",
        options: [
            "Mansion", "Apartment", "Shack", "House", "Penthouse", "Treehouse", "Houseboat",
            "Castle", "Cave", "Igloo", "Tent", "RV", "Lighthouse", "Windmill", "Barn",
            "Underground bunker", "Space station", "Tiny house", "McMansion", "Yurt",
            "Converted school bus", "Shipping container", "Hut on chicken legs", "Glass house",
            "Victorian manor", "Beach shack", "Mountain cabin", "Underwater dome", "Ice palace",
            "Floating island", "Abandoned mall", "Repurposed church", "Geodesic dome", "Hobbit hole",
            "Converted water tower", "Haunted mansion", "Farmhouse", "Airstream trailer", "Ski chalet",
            "Tropical bungalow", "Brutalist tower", "Cottage in the woods", "Desert compound", "Stilt house",
            "A very large shoe", "A really nice cardboard box", "Abandoned theme park", "Converted missile silo",
            "Monastery", "Old firehouse", "Beachfront property (eroding rapidly)", "Houseboat that can't move",
            "Studio apartment", "Loft", "Duplex", "Townhouse", "Condo", "Ranch house", "Colonial",
            "Split-level", "A-frame cabin", "Log cabin", "Earth ship", "Straw bale house", "Cob house",
            "Tree fort", "Garden shed", "Garage", "Attic", "Basement", "Crawl space", "Van down by the river",
            "Dumpster (luxury)", "Public library (after hours)", "IKEA display room", "Hotel room (permanent)",
            "Motel", "Hostel", "Commune", "Kibbutz", "Ashram", "Monastery cell", "Prison cell (unjustly)",
            "Palace", "Villa", "Chateau", "Manor", "Estate", "Plantation house", "Hacienda",
            "Adobe house", "Pueblo", "Longhouse", "Roundhouse", "Pagoda", "Temple", "Shrine",
            "Grotto", "Cavern", "Mine shaft", "Sewer (surprisingly nice)", "Subway car", "Train car",
            "Boxcar", "Caboose", "Double-decker bus", "Fire truck", "Ambulance", "Hearse (converted)",
            "Boat", "Yacht", "Sailboat", "Catamaran", "Barge", "Ferry", "Cruise ship cabin",
            "Submarine", "Bathysphere", "Diving bell", "Oil rig", "Fishing shack", "Boathouse",
            "Beach house", "Beach condo", "Surf shack", "Tiki hut", "Palapa", "Cabana",
            "Tree platform", "Nest (very large)", "Burrow", "Warren", "Den", "Lair",
            "Hideout", "Secret base", "Fort", "Bunker", "Pillbox", "Watchtower", "Turret",
            "Keep", "Citadel", "Fortress", "Stronghold", "Bastion", "Rampart", "Parapet",
            "Penthouse suite", "Penthouse loft", "Rooftop apartment", "Garden apartment", "Basement apartment",
            "Railroad apartment", "Shotgun house", "Bungalow", "Cottage", "Cabin", "Lodge",
            "Inn", "Bed and breakfast", "Tavern (upstairs)", "Pub (upstairs)", "Restaurant (upstairs)",
            "Store (upstairs)", "Shop (upstairs)", "Office (illegally)", "Warehouse loft", "Factory loft",
            "Mill loft", "Silo (converted)", "Grain elevator", "Water tower apartment", "Clock tower",
            "Bell tower", "Observation tower", "Radio tower platform", "Cell tower platform", "Billboard (behind)",
            "Overpass (under)", "Bridge (under)", "Viaduct (in)", "Aqueduct (in)", "Tunnel (in)",
            "Culvert", "Drainage pipe", "Storm drain", "Sewer pipe", "Air duct",
            "Ventilation shaft", "Elevator shaft", "Stairwell", "Hallway", "Corridor",
            "Alley", "Dead end", "Cul-de-sac", "Parking lot", "Parking garage",
            "Storage unit", "Locker", "Closet", "Pantry", "Cupboard", "Cabinet",
            "Drawer", "Box", "Crate", "Barrel", "Basket", "Hamper",
            "Trunk", "Chest", "Coffer", "Casket (empty)", "Coffin (empty)", "Sarcophagus (empty)",
            "Mausoleum", "Tomb", "Crypt", "Catacomb", "Ossuary", "Charnel house"
        ]
    },
    spouse: {
        title: "Spouse",
        options: [
            "Your high school crush", "A famous actor", "The mailman", "Your best friend", "A mysterious stranger",
            "Someone you met on the internet", "Your rival", "A time traveler", "An AI", "A ghost",
            "Your dentist", "Someone who doesn't speak your language", "A clone of yourself", "Your boss",
            "Someone from a different century", "A cryptid", "Your Uber driver", "A reformed villain",
            "Someone you've never met", "Your ex's best friend", "A talking animal", "Someone invisible",
            "Your parallel universe self", "A wax statue that came to life", "The moon (personified)",
            "Someone who thinks they're a vampire (they're not)", "A very ambitious mime", "Your sleep paralysis demon",
            "Someone who exclusively communicates in riddles", "A professional whistler", "Your childhood imaginary friend",
            "Someone allergic to everything", "A former cult leader (reformed)", "Your doctor",
            "Someone who collects teeth", "A haunted doll", "Your nemesis", "Someone incredibly average",
            "A retired spy", "Someone who won't stop talking about their podcast", "Your landlord",
            "Someone from witness protection", "A shapeshifter stuck in one form", "Your coworker",
            "Someone who thinks everything is a conspiracy", "A professional video game player", "Your therapist",
            "Someone who insists they invented Bitcoin", "A method actor who won't break character", "Your mechanic",
            "Your barista", "Your hairdresser", "Your dog walker", "Your personal trainer", "Your yoga instructor",
            "Your pilates instructor", "Your life coach", "Your career counselor", "Your financial advisor", "Your accountant",
            "Your lawyer", "Your real estate agent", "Your insurance agent", "Your travel agent", "Your wedding planner",
            "Your party planner", "Your event coordinator", "Your publicist", "Your agent", "Your manager",
            "Your assistant", "Your intern", "Your apprentice", "Your mentee", "Your protégé",
            "Your rival's rival", "Your enemy's enemy", "Your friend's friend", "Your cousin's cousin", "Your neighbor's neighbor",
            "The person in the mirror", "Your reflection", "Your shadow", "Your echo", "Your footsteps",
            "The voice in your head", "Your inner child", "Your future self", "Your past self", "Your alternate self",
            "Someone who looks exactly like you", "Someone who acts exactly like you", "Someone who thinks exactly like you",
            "Your doppelganger", "Your evil twin", "Your good twin", "Your identical twin", "Your fraternal twin",
            "Your conjoined twin (separated)", "Your sibling", "Your half-sibling", "Your step-sibling", "Your adopted sibling",
            "Your foster sibling", "Your cousin", "Your second cousin", "Your third cousin", "Your distant cousin",
            "Your in-law", "Your future in-law", "Your ex-in-law", "Your almost-in-law", "Your could-have-been-in-law",
            "A stranger on a train", "A stranger on a plane", "A stranger on a bus", "A stranger on a boat",
            "A stranger on the street", "A stranger in a bar", "A stranger in a café", "A stranger in a library",
            "A stranger in a bookstore", "A stranger in a museum", "A stranger in a park", "A stranger at a concert",
            "A stranger at a festival", "A stranger at a wedding", "A stranger at a funeral", "A stranger at a party",
            "Someone you met in line", "Someone you met at jury duty", "Someone you met at the DMV",
            "Someone you met at a protest", "Someone you met at a rally", "Someone you met at a march",
            "Someone you met volunteering", "Someone you met traveling", "Someone you met backpacking",
            "Someone you met hitchhiking", "Someone you met at a hostel", "Someone you met at a resort",
            "Someone you met at summer camp", "Someone you met at space camp", "Someone you met at band camp",
            "Someone you met at debate camp", "Someone you met at math camp", "Someone you met at art camp",
            "Someone who loves pineapple on pizza", "Someone who hates pineapple on pizza",
            "Someone who's never had pizza", "Someone who's never left their hometown", "Someone who's been everywhere",
            "Someone who collects something weird", "Someone who's afraid of something silly",
            "Someone who's really into astrology", "Someone who doesn't believe in astrology",
            "A Gemini (sorry)", "A Scorpio (intense)", "A Virgo (judgmental)", "An Aries (impulsive)",
            "A Taurus (stubborn)", "A Cancer (moody)", "A Leo (dramatic)", "A Libra (indecisive)",
            "A Sagittarius (commitment issues)", "A Capricorn (workaholic)", "An Aquarius (aloof)", "A Pisces (dreamy)",
            "Someone born on a leap day", "Someone born during an eclipse", "Someone born during a storm",
            "Someone born in a taxi", "Someone born on a plane", "Someone born on a boat",
            "A telepath (reading your thoughts right now)", "A precog (saw this coming)", "A psychic (real)",
            "A medium (talks to the dead)", "A channeler", "An oracle", "A seer", "A prophet",
            "Someone cursed", "Someone blessed", "Someone enchanted", "Someone bewitched", "Someone hexed"
        ]
    },
    car: {
        title: "Car",
        options: [
            "Tesla", "Toyota Camry", "Minivan", "Motorcycle", "Bicycle", "Skateboard", "Horse and buggy",
            "Lamborghini", "Tricycle", "Hoverboard", "Segway", "Hot air balloon", "Rocket ship", "Magic carpet",
            "Shopping cart", "Zamboni", "Monster truck", "Ice cream truck", "Hearse", "Invisible car",
            "Oscar Mayer Wienermobile", "Riding lawnmower", "Golf cart", "Jet ski (on land)", "Pogo stick",
            "Unicycle", "Penny-farthing", "Chariot", "Sleigh pulled by dogs", "Time machine (broken)",
            "Clown car", "Mystery Machine", "Batmobile (replica)", "PT Cruiser", "Smart car",
            "Hummer (gas mileage: concerning)", "DeLorean", "Volkswagen Beetle (the old kind)", "Sedan chair carried by servants",
            "Rickshaw", "Tuk-tuk", "Your own two feet", "Very fast snail", "Rascal scooter", "Zamboni (yes, again)",
            "Vespa", "Segway (but it's haunted)", "Extremely long limousine", "Cybertruck", "Bus pass",
            "Ferrari", "Porsche", "Corvette", "Mustang", "Camaro", "Challenger", "Charger",
            "BMW", "Mercedes", "Audi", "Lexus", "Infiniti", "Acura", "Cadillac",
            "Honda Civic", "Honda Accord", "Toyota Corolla", "Toyota Prius", "Nissan Altima", "Mazda3",
            "Subaru Outback", "Subaru Forester", "Jeep Wrangler", "Jeep Cherokee", "Ford F-150", "Chevy Silverado",
            "Ram 1500", "Toyota Tacoma", "Ford Escape", "Chevy Equinox", "Honda CR-V", "Toyota RAV4",
            "Sedan", "Coupe", "Convertible", "SUV", "Truck", "Van", "Station wagon",
            "Hatchback", "Crossover", "Sports car", "Luxury car", "Economy car", "Compact car",
            "Scooter", "Moped", "Dirt bike", "Sport bike", "Cruiser", "Chopper", "Trike",
            "ATV", "UTV", "Snowmobile", "Jet ski", "Boat", "Yacht", "Sailboat",
            "Kayak", "Canoe", "Rowboat", "Paddleboard", "Surfboard", "Skateboard (motorized)",
            "Roller skates", "Rollerblades", "Heelys", "Moon shoes", "Stilts", "Crutches",
            "Wheelchair", "Walker", "Cane", "Broom", "Mop", "Vacuum cleaner (rides)",
            "Roomba (large)", "Riding lawn mower", "Tractor", "Bulldozer", "Excavator", "Crane",
            "Forklift", "Cherry picker", "Boom lift", "Scissor lift", "Pallet jack", "Hand truck",
            "Dolly", "Cart", "Wagon", "Wheelbarrow", "Sled", "Toboggan",
            "Bobsled", "Luge", "Skeleton sled", "Soapbox racer", "Go-kart", "Bumper car",
            "Pedal car", "Power Wheels", "Big Wheel", "Green Machine", "Radio Flyer", "Little Tikes car",
            "Flintstone car (foot-powered)", "Shopping cart (souped up)", "Office chair (rolling)",
            "Swivel chair", "Rocking chair (somehow)", "La-Z-Boy (motorized)", "Couch (wheels added)",
            "Bed (wheels added)", "Desk (wheels added)", "Table (wheels added)", "Piano (on wheels)",
            "Bookshelf (on wheels)", "Filing cabinet (on wheels)", "Dumpster (motorized)", "Trash can (motorized)",
            "Recycling bin (motorized)", "Mailbox (mobile)", "Fire hydrant (mobile)", "Stop sign (mobile)",
            "Traffic light (mobile)", "Parking meter (mobile)", "Phone booth (mobile)", "Port-a-potty (mobile)",
            "Hot dog cart", "Food truck", "Coffee cart", "Flower cart", "Fruit cart",
            "Balloon cart", "Pretzel cart", "Taco truck", "Pizza truck", "Burger truck",
            "Palanquin", "Sedan chair", "Litter", "Howdah (elephant)", "Camel", "Donkey",
            "Mule", "Llama", "Alpaca", "Ostrich", "Emu", "Giant tortoise",
            "Dragon (tamed)", "Unicorn", "Pegasus", "Griffin", "Hippogriff", "Centaur (willing)",
            "Broom (flying)", "Carpet (flying)", "Umbrella (Mary Poppins style)", "Leaf (wind-powered)",
            "Cloud", "Lightning bolt (riding)", "Rainbow (sliding)", "Moonbeam", "Sunbeam",
            "Teleporter (unreliable)", "Portal gun", "Transporter (Star Trek)", "TARDIS (stolen)",
            "Beam me up Scotty", "Wormhole", "Black hole (risky)", "White hole", "Stargate"
        ]
    },
    kids: {
        title: "Kids",
        options: [
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
            "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
            "100 (you run an orphanage)", "Twins", "Triplets", "Quadruplets", "Quintuplets", "Sextuplets",
            "Lost count", "None but 47 cats", "None but 100 dogs", "None but birds", "None but fish",
            "One very large child", "Several small children of uncertain number", "Many tiny children",
            "Negative 2 (don't ask)", "Too many", "Just the right amount", "3.5 (one is half yours)",
            "A classroom full", "An even dozen", "A baker's dozen", "None but everyone thinks you have kids",
            "12 but they're all the same person at different ages", "One kid but they're incredibly difficult",
            "200 (you're a school principal)", "6 (all named the same thing)", "None (just fur babies)",
            "1 but they're actually 3 kids in a trenchcoat", "An undisclosed number", "A sensible amount",
            "More than you can afford", "Exactly as many as you have seats in your car",
            "None but lots of plants you call your babies", "17 (you started a band)", "9 (baseball team)",
            "11 (soccer team)", "30 (you teach kindergarten)", "Zero but everyone assumes you do",
            "One surprise child from the future", "Countless (time loop situation)",
            "One but they're a genius", "Five sets of twins", "An entire daycare worth",
            "Just one very tiny elephant (you don't question it)", "21", "22", "23", "24", "25",
            "30", "35", "40", "45", "50", "60", "70", "80", "90",
            "A reasonable number", "An unreasonable number", "A prime number", "A fibonacci number",
            "As many as you have toes", "As many as you have fingers", "As many as you have teeth",
            "One for each year of your life", "One for each month of the year", "One for each day of the week",
            "365 (one per day)", "52 (one per week)", "12 (one per month)", "4 (one per season)",
            "None (by choice)", "None (by chance)", "None (yet)", "None (anymore)", "None (ever)",
            "One (only child)", "Two (classic)", "Three (chaotic)", "Four (overwhelming)", "Five (brave)",
            "One set of twins", "Two sets of twins", "Three sets of twins", "One set of triplets",
            "Irish twins", "Virtual twins", "Adopted", "Fostered", "Stepchildren", "Godchildren",
            "Nieces and nephews (you're raising them)", "Your siblings' kids (long story)",
            "The neighbor's kids (they just live with you now)", "Street urchins you've taken in",
            "Orphans you've adopted", "Strays", "Foundlings", "Changelings", "Chosen ones",
            "Prophesied children", "Miracle babies", "Test tube babies", "Designer babies", "Clone babies",
            "Robot children", "AI children", "Hologram children", "Imaginary children (they're real to you)",
            "Ghost children", "Vampire children (twilight style)", "Werewolf cubs", "Witch children",
            "Wizard children", "Alien children", "Hybrid children", "Mutant children", "Super children",
            "One giant baby", "Many microscopic babies", "Invisible babies", "Incorporeal babies",
            "Babies from another dimension", "Time-displaced children", "Ageless children", "Backwards-aging children",
            "Children who age at different rates", "One child per personality", "Schrodinger's child (maybe?)"
        ]
    },
    job: {
        title: "Job",
        options: [
            "Doctor", "Lawyer", "Teacher", "Programmer", "Artist", "Chef", "Janitor", "CEO",
            "Professional napper", "Astronaut", "Detective", "Superhero", "Supervillain", "Time cop",
            "Professional mourner", "Underwater basket weaver", "Professional cuddler", "Pet psychic",
            "Pirate", "Knight", "Dragon tamer", "Cloud painter", "Professional line-stander",
            "Meme archaeologist", "Professional complainer", "Competitive eater", "Palindrome writer",
            "Emoji translator", "Professional conspiracy theorist", "Bigfoot tracker", "Ghost hunter",
            "Wizard", "Fortune teller (ironic)", "Professional sleeper for mattress testing", "Iceberg mover",
            "Professional Netflix watcher", "Cat video curator", "Dream interpreter", "Professional third wheel",
            "Influencer (0 followers)", "Taxidermist", "Beekeeper", "Storm chaser", "Puppeteer",
            "Cryptozoologist", "Professional whistler", "Food truck owner", "Museum guard", "Park ranger",
            "Lighthouse keeper", "Professional organizer", "Life coach", "Feng shui consultant", "Snake milker",
            "Professional bridesmaid for hire", "Renaissance fair performer", "Paranormal investigator",
            "Treasure hunter (unsuccessful)", "Competitive air guitarist", "Social media manager for a cat",
            "Professional gift wrapper", "Escape room designer", "Sleep scientist", "Professional procrastinator",
            "Balloon animal artist", "Voice of automated phone systems", "Professional hermit",
            "Presidential portrait artist", "Competitive cup stacker", "Beard model",
            "Nurse", "Dentist", "Veterinarian", "Pharmacist", "Physical therapist", "Occupational therapist",
            "Speech therapist", "Chiropractor", "Optometrist", "Orthodontist", "Surgeon", "Anesthesiologist",
            "Radiologist", "Pathologist", "Pediatrician", "Obstetrician", "Gynecologist", "Dermatologist",
            "Psychologist", "Psychiatrist", "Therapist", "Counselor", "Social worker", "Case manager",
            "Engineer", "Architect", "Accountant", "Banker", "Financial advisor", "Stock broker",
            "Real estate agent", "Insurance agent", "Sales representative", "Marketing manager", "Brand strategist",
            "Copywriter", "Content creator", "Graphic designer", "Web developer", "UX designer",
            "Data analyst", "Data scientist", "Machine learning engineer", "AI researcher", "Roboticist",
            "Scientist", "Researcher", "Lab technician", "Biologist", "Chemist", "Physicist",
            "Mathematician", "Statistician", "Economist", "Sociologist", "Anthropologist", "Archaeologist",
            "Historian", "Philosopher", "Theologian", "Religious scholar", "Librarian", "Archivist",
            "Curator", "Museum director", "Art dealer", "Gallery owner", "Auctioneer", "Appraiser",
            "Writer", "Author", "Novelist", "Poet", "Playwright", "Screenwriter", "Journalist",
            "Reporter", "Editor", "Publisher", "Literary agent", "Book reviewer", "Critic",
            "Musician", "Singer", "Songwriter", "Composer", "Conductor", "Music producer",
            "Sound engineer", "Audio technician", "DJ", "Radio host", "Podcast host", "Voice actor",
            "Actor", "Actress", "Director", "Producer", "Cinematographer", "Camera operator",
            "Film editor", "Video editor", "Animator", "3D modeler", "Visual effects artist", "Stunt performer",
            "Dancer", "Choreographer", "Dance instructor", "Ballet dancer", "Modern dancer", "Hip hop dancer",
            "Athlete", "Professional sports player", "Coach", "Personal trainer", "Nutritionist", "Dietitian",
            "Yoga instructor", "Pilates instructor", "Fitness instructor", "Gym owner", "Sports commentator",
            "Referee", "Umpire", "Scout", "Agent (sports)", "Team manager", "Athletic director",
            "Police officer", "Firefighter", "Paramedic", "EMT", "911 operator", "Dispatcher",
            "Security guard", "Bodyguard", "Private investigator", "Bounty hunter", "Process server",
            "Bailiff", "Court reporter", "Judge", "Magistrate", "Prosecutor", "Defense attorney",
            "Paralegal", "Legal assistant", "Notary public", "Mediator", "Arbitrator", "Lobbyist",
            "Politician", "Senator", "Congressperson", "Mayor", "Governor", "President (of something)",
            "Diplomat", "Ambassador", "Foreign service officer", "Intelligence analyst", "Spy",
            "Military officer", "Soldier", "Sailor", "Airman", "Marine", "Coast Guard",
            "Pilot", "Co-pilot", "Flight attendant", "Air traffic controller", "Airport security",
            "TSA agent", "Customs officer", "Border patrol", "Immigration officer", "Postal worker",
            "Mail carrier", "Delivery driver", "Truck driver", "Bus driver", "Taxi driver",
            "Uber driver", "Lyft driver", "Train conductor", "Train engineer", "Subway operator",
            "Ship captain", "First mate", "Deckhand", "Sailor", "Fisherman", "Whaler (unethical)",
            "Carpenter", "Plumber", "Electrician", "HVAC technician", "Mechanic", "Auto mechanic",
            "Welder", "Machinist", "Factory worker", "Assembly line worker", "Quality control inspector",
            "Construction worker", "Roofer", "Mason", "Concrete finisher", "Drywaller", "Painter",
            "Landscaper", "Gardener", "Groundskeeper", "Arborist", "Tree surgeon", "Lumberjack",
            "Farmer", "Rancher", "Agricultural worker", "Dairy farmer", "Chicken farmer", "Pig farmer",
            "Crop farmer", "Organic farmer", "Hydroponics farmer", "Vertical farmer", "Urban farmer",
            "Florist", "Plant nursery owner", "Seed seller", "Fertilizer specialist", "Pest control",
            "Exterminator", "Animal control officer", "Dog catcher", "Wildlife rehabilitator", "Zookeeper",
            "Aquarium keeper", "Marine biologist", "Oceanographer", "Meteorologist", "Climatologist",
            "Geologist", "Seismologist", "Volcanologist", "Paleontologist", "Astronomer", "Astrophysicist"
        ]
    },
    location: {
        title: "Location",
        options: [
            "New York", "Los Angeles", "London", "Paris", "Tokyo", "Dubai", "Sydney", "Toronto",
            "Antarctica", "The Moon", "Mars", "A deserted island", "Atlantis", "Narnia", "Hogwarts",
            "The Upside Down", "Middle Earth", "Gotham City", "A parallel dimension", "Your hometown (you never left)",
            "The bottom of the ocean", "International waters", "The North Pole", "A floating city",
            "Underground", "The Matrix", "A simulation", "Witness protection in Iowa", "A nice suburb",
            "A compound in the woods", "International Space Station", "A place that doesn't exist yet",
            "Nowhere specific (you're a nomad)", "Bermuda Triangle", "Area 51", "A volcano (active)",
            "The Metaverse", "A Renaissance fair (permanent resident)", "A cruise ship that never docks",
            "Siberia", "Death Valley", "The Amazon Rainforest", "A haunted New England village",
            "Las Vegas", "A ski resort town", "A beach town that's slowly sinking", "The cloud (literally)",
            "A space station orbiting Jupiter", "A biodome on Mars", "Inside a video game", "A pocket dimension",
            "The Twilight Zone", "A timeline that got pruned but you survived", "Seattle (it never stops raining)",
            "Phoenix (it never stops being hot)", "A small town with a dark secret", "The place time forgot",
            "A rest stop off I-95", "An abandoned shopping mall", "Inside a whale (Jonah-style)", "The backrooms",
            "A very fancy airport lounge", "A monastery in Tibet", "A lighthouse in Maine", "Literally nowhere (the void)",
            "Gary, Indiana", "A houseboat in Amsterdam", "An ashram in India", "A castle in Scotland",
            "A favela in Rio", "A hutong in Beijing", "Somewhere without Wi-Fi (nightmare)",
            "Chicago", "Boston", "Philadelphia", "San Francisco", "Miami", "Atlanta", "Dallas",
            "Houston", "Austin", "Denver", "Portland", "Seattle", "Minneapolis", "Detroit",
            "Washington DC", "Baltimore", "Nashville", "Memphis", "New Orleans", "St. Louis",
            "Kansas City", "Oklahoma City", "San Antonio", "Phoenix", "Las Vegas", "Salt Lake City",
            "Albuquerque", "Tucson", "San Diego", "Sacramento", "Oakland", "San Jose", "Fresno",
            "Berlin", "Rome", "Madrid", "Barcelona", "Amsterdam", "Copenhagen", "Stockholm",
            "Oslo", "Helsinki", "Prague", "Vienna", "Budapest", "Warsaw", "Krakow",
            "Athens", "Istanbul", "Moscow", "St. Petersburg", "Kiev", "Bucharest", "Sofia",
            "Cairo", "Marrakech", "Casablanca", "Nairobi", "Cape Town", "Johannesburg", "Lagos",
            "Accra", "Dakar", "Addis Ababa", "Dar es Salaam", "Kampala", "Kigali", "Kinshasa",
            "Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai", "Hyderabad", "Pune",
            "Bangkok", "Manila", "Jakarta", "Singapore", "Kuala Lumpur", "Ho Chi Minh City", "Hanoi",
            "Seoul", "Busan", "Taipei", "Hong Kong", "Macau", "Shanghai", "Beijing",
            "Guangzhou", "Shenzhen", "Chengdu", "Xi'an", "Wuhan", "Nanjing", "Hangzhou",
            "Mexico City", "Guadalajara", "Monterrey", "Tijuana", "Cancun", "Playa del Carmen",
            "Buenos Aires", "São Paulo", "Rio de Janeiro", "Lima", "Bogotá", "Santiago",
            "Caracas", "Quito", "La Paz", "Montevideo", "Asunción", "Brasília", "Havana",
            "Alaska", "Hawaii", "Puerto Rico", "Guam", "American Samoa", "Virgin Islands",
            "Greenland", "Iceland", "Faroe Islands", "Svalbard", "Madagascar", "Mauritius",
            "Seychelles", "Maldives", "Fiji", "Tahiti", "Bora Bora", "New Zealand",
            "Tasmania", "Perth", "Melbourne", "Brisbane", "Adelaide", "Canberra", "Wellington",
            "The Arctic", "The Antarctic", "The Sahara", "The Gobi", "The Mojave", "The Atacama",
            "The Himalayas", "The Alps", "The Andes", "The Rockies", "The Appalachians", "The Pyrenees",
            "The Amazon", "The Congo", "The Nile", "The Mississippi", "The Ganges", "The Mekong",
            "The Great Barrier Reef", "The Dead Sea", "The Grand Canyon", "Yosemite", "Yellowstone",
            "The Everglades", "Death Valley", "Monument Valley", "Antelope Canyon", "Bryce Canyon",
            "Zion", "Arches", "Canyonlands", "Mesa Verde", "Great Sand Dunes", "Rocky Mountain",
            "In a van", "In an RV", "On a boat", "In a tent", "In a yurt", "In a tipi",
            "In a camper", "In a trailer", "In a motorhome", "In a converted bus", "In a tiny house on wheels",
            "Nomadic", "Traveling", "Wandering", "Drifting", "Roaming", "Vagabond", "Hobo",
            "The road", "The rails", "The sea", "The sky", "The stars", "The cosmos",
            "Everywhere", "Nowhere", "Anywhere", "Somewhere", "Here", "There", "Beyond"
        ]
    },
    salary: {
        title: "Annual Salary",
        options: [
            "$20,000", "$35,000", "$50,000", "$75,000", "$100,000", "$150,000", "$250,000", "$500,000",
            "$1 million", "$10 million", "$100 million", "$1 billion", "$0 (you live off the land)",
            "$12,000 (minimum wage)", "$45,000", "$85,000", "$120,000", "$200,000", "$350,000",
            "$2 million", "$5 million", "$50 million", "Whatever you find in couch cushions",
            "$7.50 per hour", "One Bitcoin (value fluctuates wildly)", "Paid in exposure",
            "Unlimited breadsticks", "Room and board only", "$25,000 but full benefits",
            "$90,000", "$65,000", "$180,000", "$400,000", "$750,000", "$15 million",
            "Enough to get by", "More than you need", "Less than you deserve", "Paid in eggs and milk",
            "$30,000 (plus tips)", "$55,000", "$95,000", "$140,000", "$225,000", "$600,000",
            "Wealth beyond measure", "Comfortable but not rich", "Barely scraping by", "$42,069 (nice)",
            "Paid in compliments", "Three chickens a week", "$1 per year (you're doing it for passion)",
            "$80,000", "$110,000", "$175,000", "$300,000", "$1.5 million", "Paid in company stock (worthless)",
            "Monopoly money", "Enough to retire immediately", "Not enough to retire ever", "Cryptocurrency (dubious)",
            "$60,000", "$88,000", "$125,000", "$190,000", "$280,000", "$450,000", "$800,000",
            "$15,000", "$18,000", "$22,000", "$27,000", "$32,000", "$38,000", "$42,000",
            "$48,000", "$52,000", "$58,000", "$62,000", "$68,000", "$72,000", "$78,000",
            "$82,000", "$92,000", "$98,000", "$105,000", "$115,000", "$135,000", "$145,000",
            "$155,000", "$165,000", "$185,000", "$195,000", "$210,000", "$230,000", "$240,000",
            "$260,000", "$270,000", "$290,000", "$310,000", "$320,000", "$340,000", "$360,000",
            "$380,000", "$420,000", "$440,000", "$460,000", "$480,000", "$520,000", "$540,000",
            "$560,000", "$580,000", "$620,000", "$640,000", "$660,000", "$680,000", "$700,000",
            "$720,000", "$740,000", "$760,000", "$780,000", "$820,000", "$840,000", "$860,000",
            "$880,000", "$900,000", "$920,000", "$940,000", "$960,000", "$980,000", "$1.1 million",
            "$1.2 million", "$1.3 million", "$1.4 million", "$1.6 million", "$1.7 million", "$1.8 million",
            "$1.9 million", "$2.1 million", "$2.2 million", "$2.3 million", "$2.4 million", "$2.5 million",
            "$2.6 million", "$2.7 million", "$2.8 million", "$2.9 million", "$3 million", "$3.5 million",
            "$4 million", "$4.5 million", "$6 million", "$7 million", "$8 million", "$9 million",
            "$11 million", "$12 million", "$13 million", "$14 million", "$16 million", "$17 million",
            "$18 million", "$19 million", "$20 million", "$25 million", "$30 million", "$35 million",
            "$40 million", "$45 million", "$60 million", "$70 million", "$80 million", "$90 million",
            "$110 million", "$120 million", "$130 million", "$140 million", "$150 million", "$200 million",
            "$250 million", "$300 million", "$350 million", "$400 million", "$450 million", "$500 million",
            "$600 million", "$700 million", "$800 million", "$900 million", "$1.5 billion", "$2 billion",
            "$5 billion", "$10 billion", "$50 billion", "$100 billion", "More money than God",
            "Paid in gold bars", "Paid in silver coins", "Paid in precious gems", "Paid in fine art",
            "Paid in real estate", "Paid in livestock", "Paid in crops", "Paid in handshakes",
            "Paid in IOUs", "Paid in promises", "Paid in good vibes", "Paid in karma points",
            "Paid in airline miles", "Paid in hotel points", "Paid in gift cards", "Paid in coupons",
            "Paid in Monopoly money (literally)", "Paid in Chuck E. Cheese tokens", "Paid in arcade tickets",
            "Paid in bottle caps (Fallout economy)", "Paid in bottlecaps (beach finds)", "Paid in seashells",
            "Paid in pebbles", "Paid in leaves", "Paid in acorns", "Paid in pinecones", "Paid in sticks",
            "Paid in berries", "Paid in mushrooms (sketchy)", "Paid in truffles (fancy)", "Paid in caviar",
            "Paid in champagne", "Paid in wine", "Paid in beer", "Paid in coffee", "Paid in tea",
            "Indentured servitude", "Slavery (illegal)", "Volunteer (unpaid)", "Intern (exploited)",
            "Negative salary (you pay them)", "You owe money to work here", "It costs to have this job"
        ]
    }
};
